common: &common
  adapter: postgresql
  username: postgres
  password: postgres # from psql setup, see Postgresql

development:
  <<: *common
  database: developmentdb

test:
  <<: *common
  database: testdb

production:
  <<: *common
  database: productiondb
